announcements/announcements/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

announcements/board/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import (BoardFiltered, BoardMy, AnnDetail, AnnCreate, AnnUpdate, RespCreate, RespDetail, RespMy,
                    resp_acc, resp_rej, mass_mail)

urlpatterns = [
   # path — означает путь.
   # В данном случае путь ко всем товарам у нас останется пустым,
   # чуть позже станет ясно почему.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
   path('', BoardFiltered.as_view(), name='board'),
   path('my/', BoardMy.as_view(), name='my_ann'),
   path('<int:pk>/', AnnDetail.as_view(), name='detail'),
   path('create/', AnnCreate.as_view(), name='create'),
   path('<int:pk>/update', AnnUpdate.as_view(), name='update'),
   path('<int:pk>/response', RespCreate.as_view(), name='response'),
   path('response/<int:pk>', RespDetail.as_view(), name='resp_det'),
   path('response/<int:pk>/acc', resp_acc, name='accept'),
   path('response/<int:pk>/rej', resp_rej, name='reject'),
   path('response/my', RespMy.as_view(), name='resp_my'),
   path('massmail/', mass_mail, name='massmail'),
   ]

announcements/board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

class Announcement(models.Model):
    tank = 'TN'
    hil = 'HL'
    dd = 'DD'
    torg = 'TG'
    gildm = 'GM'
    kvestg = 'KG'
    kuzn = 'KZ'
    kozhev = 'KV'
    zelev = 'ZL'
    zakl = 'MZ'
    POSITIONS = [
        (tank, 'Танк'),
        (hil, 'Хил'),
        (dd, 'ДД'),
        (torg, 'Торговец'),
        (gildm, 'Гилдмастер'),
        (kvestg, 'Квестгивер'),
        (kuzn, 'Кузнец'),
        (kozhev, 'Кожевник'),
        (zelev, 'Зельевар'),
        (zakl, 'Мастер заклинаний'),
    ]
    type = models.CharField(max_length=2, choices=POSITIONS, default=tank)
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    text = RichTextUploadingField()
    time_creating = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('detail', args=[str(self.id)])

class Response(models.Model):
    waiting = 'W'
    accepted = 'A'
    rejected = 'R'
    POSITIONS = [
        (waiting, 'На рассмотрении'),
        (accepted, 'Принят'),
        (rejected, 'Удален'),
    ]
    announcement = models.ForeignKey(Announcement, blank=True, null=True, on_delete=models.CASCADE)
    responser = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    text = models.TextField()
    status = models.CharField(max_length=1, choices=POSITIONS, default=waiting)
    time_creating = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('resp_det', args=[str(self.id)])

announcements/board/forms.py
from django import forms
from .models import Announcement, Response

class AnnForm(forms.ModelForm):
    class Meta:
        model = Announcement
        fields = [
            'type',
            'title',
            'text',
        ]
class RespForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = ['text']

class MailForm(forms.Form):
    subject = forms.CharField(label='Тема', required=True)
    text = forms.CharField(label='Сообщение', required=True)

announcements/board/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.core.mail import send_mail
from django.dispatch import receiver
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponse
from django.shortcuts import redirect
from .models import Announcement, Response
from .filters import BoardFilter, RespFilter
from .forms import AnnForm, RespForm, MailForm

class BoardFiltered(ListView):
    model = Announcement
    ordering = '-time_creating'
    template_name = 'board.html'
    context_object_name = 'anns'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = BoardFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context

class BoardMy(LoginRequiredMixin, ListView):
    model = Announcement
    ordering = '-time_creating'
    template_name = 'boardmy.html'
    context_object_name = 'anns'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = BoardFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        context['user_id'] = self.request.user.id
        return context

class AnnDetail(DetailView):
    model = Announcement
    template_name = 'ann_d.html'
    context_object_name = 'ann'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if (self.object.author == self.request.user or
                Response.objects.filter(announcement=self.object, responser=self.request.user).exists()):
            resp = False
        else:
            resp = True
        context['resp'] = resp
        return context

class AnnCreate(LoginRequiredMixin, CreateView):
    form_class = AnnForm
    model = Announcement
    template_name = 'ann_edit.html'

    def form_valid(self, form):
        result = super().form_valid(form)
        self.object.author = self.request.user
        self.object.save()
        return result

class AnnUpdate(LoginRequiredMixin, UpdateView):
    form_class = AnnForm
    model = Announcement
    template_name = 'ann_edit.html'

    def get_object(self, queryset=None):
        initial = super(AnnUpdate, self).get_object(queryset)
        if initial.author != self.request.user:
            raise PermissionDenied('Разрешено редактировать только свои объявления')
        return initial


class RespCreate(LoginRequiredMixin, CreateView):
    form_class = RespForm
    model = Response
    template_name = 'resp_edit.html'

    def form_valid(self, form):
        result = super().form_valid(form)
        self.object.responser = self.request.user
        if Announcement.objects.filter(id=self.kwargs['pk']).exists():
            ann = Announcement.objects.get(id=self.kwargs['pk'])
        else:
            self.object.delete()
            raise Http404('Вы пытаетесь откликнуться на несуществующее объявление')
        self.object.announcement = ann
        if self.object.responser == self.object.announcement.author:
            self.object.delete()
            raise Http404('Вы пытаетесь откликнуться на собственное объявление')
        if Response.objects.filter(announcement=self.object.announcement, responser=self.object.responser):
            self.object.delete()
            raise Http404('Вы уже откликались на это объявление')
        self.object.save()
        lst=[]
        lst.append(self.object.announcement.author.email)
        send_mail(
            subject=f'Новый отклик!',
            message=f'Дорогой {self.object.announcement.author.username}, на ваше объявление'
                    f'{self.object.announcement.title} получен новый отклик от'
                    f'пользователя {self.object.responser.username}',
            from_email='da3c709e-298c-4bc6-98b5-30bfc7892069@debugmail.io',
            recipient_list=lst
        )
        return result

class RespDetail(DetailView):
    model = Response
    template_name = 'resp_d.html'
    context_object_name = 'resp'

class RespMy(LoginRequiredMixin, ListView):
    model = Response
    ordering = '-time_creating'
    template_name = 'respmy.html'
    context_object_name = 'resps'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = RespFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        context['user_id'] = self.request.user.id
        return context

@login_required
def resp_acc(request, **kwargs):
    user = request.user
    resp_id = kwargs.get('pk')
    if Response.objects.filter(id=resp_id).exists():
        resp = Response.objects.get(id=resp_id)
    else:
        raise Http404('Такого отклика не существует')
    if resp.announcement.author == user:
        resp.status = Response.accepted
    else:
        raise PermissionDenied('У вас нет прав на изменение статуса этого отклика')
    resp.save()
    lst = []
    lst.append(resp.responser.email)
    send_mail(
        subject=f'Ваш отклик принят!',
        message=f'Дорогой {resp.responser.username}, ваш отклик на объявление {resp.announcement.title} принят'
                f'автором объявления {resp.announcement.author.username}',
        from_email='da3c709e-298c-4bc6-98b5-30bfc7892069@debugmail.io',
        recipient_list=lst
    )
    return redirect('resp_my')

@login_required
def resp_rej(request, **kwargs):
    user = request.user
    resp_id = kwargs.get('pk')
    if Response.objects.filter(id=resp_id).exists():
        resp = Response.objects.get(id=resp_id)
    else:
        raise Http404('Такого отклика не существует')
    if resp.announcement.author == user:
        resp.status = Response.rejected
    else:
        raise PermissionDenied('У вас нет прав на изменение статуса этого отклика')
    resp.save()
    return redirect('resp_my')

@login_required
def mass_mail(request, **kwargs):
    if not request.user.is_staff:
        raise PermissionDenied('У вас нет прав на это действие')
    if request.method == 'GET':
        form = MailForm()
    elif request.method == 'POST':
        form = MailForm(request.POST)
        lst = []
        users = User.objects.all()
        for i in users:
            lst.append(i.email)
        if form.is_valid():
            send_mail(
                subject=form.cleaned_data['subject'],
                message=form.cleaned_data['text'],
                from_email='da3c709e-298c-4bc6-98b5-30bfc7892069@debugmail.io',
                recipient_list=lst
            )
        else:
            raise PermissionDenied('Неверный запрос')
        return redirect('board')
    return render(request, 'mail.html', {'form': form})

announcements/templates/ann_d.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'default.html' %}


<!-- Название у нас будет Product -->
{% block title %}
ann
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ ann.title }}</h1>
{{ form.media }}
Дата публикации {{ ann.time_creating|date:'d M Y' }}<br>
Категория {{ ann.get_type_display }}<br>
{{ ann.text|safe }}<br>
{% if resp %}<button> <a href="{% url 'response' ann.pk %}"> Откликнуться </a></button><br>{% endif %}
<button> <a href="{% url 'board' %}"> Доска объявлений </a></button>
{% endblock content %}

announcements/templates/ann_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Объявления</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

announcements/templates/board.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'default.html' %}
{% load custom_tags %}

<!-- Название у нас будет products -->
{% block title %}
anns
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все объявления</h1>
   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>
<button> <a href="{% url 'create' %}"> Создать новое </a></button>
<button> <a href="{% url 'my_ann' %}"> Мои объявления </a></button>
<button> <a href="{% url 'resp_my' %}"> Отклики </a></button>
<!-- Выводим товары, только если они есть с помощью тега if -->
    {% if anns %}
        <table align="center">
            <tr>
                <td>Заголовок</td>
                <td>Категория</td>
                <td>Автор</td>
                <td>Дата публикации</td>
                <td>Содержание</td>
            </tr>
            {% for ann in anns %}
            <tr>
                <td><a href="{% url 'detail' ann.pk %}">{{ ann.title }}</a></td>
                <td>{{ ann.get_type_display }}</td>
                <td>{{ ann.author }}</td>
                <td>{{ ann.time_creating|date:'d M Y' }}</td>
                <td>{{ ann.text|truncatewords:20 }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Объявлений нет!</h2>
    {% endif %}

  {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

announcements/templates/boardmy.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'default.html' %}
{% load custom_tags %}

<!-- Название у нас будет products -->
{% block title %}
anns
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Мои объявления</h1>
   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>
<!-- Выводим товары, только если они есть с помощью тега if -->
    {% if anns %}
        <table align="center">
            <tr>
                <td>Заголовок</td>
                <td>Категория</td>
                <td>Автор</td>
                <td>Дата публикации</td>
                <td>Содержание</td>
            </tr>
            {% for ann in anns %}
            {% if ann.author.id == user_id %}
            <tr>
                <td>{{ ann.title }}</td>
                <td>{{ ann.get_type_display }}</td>
                <td>{{ ann.author }}</td>
                <td>{{ ann.time_creating|date:'d M Y' }}</td>
                <td>{{ ann.text|truncatewords:20 }}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </table>
    {% else %}
        <h2>Объявлений нет!</h2>
    {% endif %}
<button> <a href="{% url 'board' %}"> Доска объявлений </a></button><br>
  {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

announcements/templates/default.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Bare - Start Bootstrap Template</title>
        {% load static %}

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <div class="container">
            <a class="navbar-brand" href="#">Django tutorial</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
</nav>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    {% block content %}
                    {{ flatpage.content }}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </body>
</html>

announcements/templates/mail.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'default.html' %}
{% load custom_tags %}

<!-- Название у нас будет products -->
{% block title %}
Рассылка почты
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Рассылка почты</h1>
   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="post">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {% csrf_token %}
       {{ form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Отправить" />
   </form>
{% endblock content %}

announcements/templates/news.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'default.html' %}
{% load custom_filters %}

<!-- Название у нас будет products -->
{% block title %}
Posts
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все новости и статьи</h1>
<!-- Выводим товары, только если они есть с помощью тега if -->
    {% if posts %}
        Общее количество новостей и статей на портале
        {{ posts|length }}
        <table align="center">
            <tr>
                <td>Заголовок</td>
                <td>Дата публикации</td>
                <td>Превью</td>
            </tr>
            {% for post in posts %}
            <tr>
                <td>{{ post.title }}</td>
                <td>{{ post.time_creating|date:'d M Y' }}</td>
                <td>{{ post.text|truncatewords:20|censor }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей и статей нет!</h2>
    {% endif %}

  {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

announcements/templates/post_created_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Добрый день, вышел новый материал в категории, на которую Вы подписаны.</h2>
    <p> Название материала: {{ post.title }}<br>
        Текст: {{ post.text|truncatechars:50 }} </p>
    <a href="{% url 'Detail' post.id %}"> Читать полностью </a>
</body>
</html>

announcements/templates/posts_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление статей и новостей</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

announcements/templates/resp_d.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'default.html' %}


<!-- Название у нас будет Product -->
{% block title %}
Информация об отклике
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ resp.announcement.title }}</h1>
Текст отклика {{ resp.text }}<br>
Дата публикации {{ resp.time_creating|date:'d M Y' }}<br>
Категория {{ resp.announcement.get_type_display }}<br>
Статус {{ resp.get_status_display }}<br>
{{ ann.text }}<br>

{% endblock content %}

announcements/templates/resp_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Объявления</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

announcements/templates/respmy.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'default.html' %}
{% load custom_tags %}

<!-- Название у нас будет products -->
{% block title %}
resps
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Отклики на мои объявления</h1>
   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>
<!-- Выводим товары, только если они есть с помощью тега if -->
    {% if resps %}
        <table align="center">
            <tr>
                <td>Текст</td>
                <td>Время отклика</td>
                <td>Заголовок объявления</td>
                <td>Категория</td>
                <td>Статус</td>>
                <td></td>
            </tr>
            {% for resp in resps %}
            {% if resp.announcement.author.id == user_id %}
            <tr>
                <td>{{ resp.text }}</td>
                <td>{{ resp.time_creating|date:'d M Y' }}</td>
                <td>{{ resp.announcement.title }}</td>
                <td>{{ resp.announcement.get_type_display }}</td>
                <td>{{ resp.get_status_display }}</td>
                <td>{% if resp.status == 'W' %}
                    <button> <a href="{% url 'accept' resp.pk %}"> Принять </a></button>
                    <button> <a href="{% url 'reject' resp.pk %}"> Отклонить </a></button>
                    {% endif %}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </table>
    {% else %}
        <h2>Откликов нет!</h2>
    {% endif %}
<button> <a href="{% url 'board' %}"> Доска объявлений </a></button><br>
  {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

announcements/templates/weekly_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Добрый день, за прошедшую неделю вышел новый материал в категории, на которую Вы подписаны.</h2>
    {% for post in posts %}
    <p> Название материала: {{ post.title }}<br>
    <a href="{{ post.get_absolute_url }}"> Читать полностью </a>
    {% endfor %}
</body>
</html>